[package]
name = "rust_dot_simd"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"

[build-dependencies]
cc = "1.0"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "dot_simd_benchmark"
harness = false


